"""
predict.py — single-sequence host prediction from a PB2 amino-acid sequence.

Usage (CLI):
    python scripts/predict.py MERIKELRDLMSQSRTREILTKTTVDHMAIIKKYTSGRQEKNPSLRMKWMMAMKYPITADKRITEMI...

Usage (importable):
    from scripts.predict import predict_host
    result = predict_host("MERIKEL...")
    # {"host": "human", "probabilities": {"avian": 0.03, "human": 0.91, "mammal": 0.06}}

Requirements:
    pip install fair-esm torch scikit-learn joblib numpy biopython

Model file:
    results/baseline/pb2_rf_classifier.joblib
    — generated by running Stage 1 of notebooks/pb2_host_prediction.ipynb
      on real GISAID data. Not shipped in this repository; see README.

Data notice:
    The classifier was trained on influenza A / H5N1 PB2 sequences obtained
    from the GISAID EpiFlu database. GISAID's access agreement prohibits
    redistribution of the sequences and derived embeddings. The model weights
    (random forest split thresholds) are shared here for research use only.
    Users must have independently agreed to the GISAID Terms of Use before
    using this model on GISAID-derived sequences.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import torch
import joblib

# Resolve paths relative to the repo root regardless of where the script
# is called from.
_REPO_ROOT = Path(__file__).resolve().parent.parent
_MODEL_PATH = _REPO_ROOT / "results" / "baseline" / "pb2_rf_classifier.joblib"
_ESM2_MODEL_NAME = "esm2_t33_650M_UR50D"

_LABEL_ORDER = ["avian", "human", "mammal"]   # matches LabelEncoder used at train time


def _load_esm2(device: torch.device):
    """Load ESM-2 (downloaded to ~/.cache/torch/hub/checkpoints/ on first run)."""
    import esm
    model, alphabet = esm.pretrained.__dict__[_ESM2_MODEL_NAME]()
    model = model.eval().to(device)
    return model, alphabet


def _embed_sequence(sequence: str, model, alphabet, device: torch.device) -> np.ndarray:
    """Return a 1280-dim mean-pooled embedding for one amino-acid sequence."""
    batch_converter = alphabet.get_batch_converter()
    _, _, tokens = batch_converter([("query", sequence)])
    tokens = tokens.to(device)

    with torch.no_grad():
        results = model(tokens, repr_layers=[33], return_contacts=False)

    token_repr = results["representations"][33]          # (1, L+2, 1280)
    seq_len = (tokens != alphabet.padding_idx).sum().item()

    if seq_len > 2:
        # Exclude <cls> (position 0) and <eos> (position seq_len-1)
        residue_emb = token_repr[0, 1 : seq_len - 1]    # (L, 1280)
    else:
        residue_emb = token_repr[0, :seq_len]

    return residue_emb.mean(0).cpu().numpy()             # (1280,)


def predict_host(sequence: str, model_path: Path = _MODEL_PATH) -> dict:
    """
    Predict the host class of an influenza A PB2 amino-acid sequence.

    Parameters
    ----------
    sequence : str
        Single-letter amino-acid string (gaps and stop codons are stripped).
    model_path : Path
        Path to the saved random forest (.joblib).  Defaults to
        results/baseline/pb2_rf_classifier.joblib relative to the repo root.

    Returns
    -------
    dict with keys:
        host          : str   — predicted class ("human", "avian", or "mammal")
        probabilities : dict  — per-class probability (three floats summing to 1.0)
        sequence_length : int — number of residues after cleaning
    """
    # Sanitise input
    sequence = sequence.upper().replace("-", "").replace("*", "").replace(" ", "")
    if not sequence:
        raise ValueError("Empty sequence after cleaning.")

    if not model_path.exists():
        raise FileNotFoundError(
            f"Model not found at {model_path}.\n"
            "Run Stage 1 of notebooks/pb2_host_prediction.ipynb on real GISAID data "
            "to generate it."
        )

    rf = joblib.load(model_path)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    esm_model, alphabet = _load_esm2(device)

    embedding = _embed_sequence(sequence, esm_model, alphabet, device)   # (1280,)
    X = embedding.reshape(1, -1)

    pred_idx = int(rf.predict(X)[0])
    proba = rf.predict_proba(X)[0]                       # shape (3,) — avian, human, mammal

    # rf.classes_ matches the LabelEncoder used at train time: [0, 1, 2] → avian, human, mammal
    host = _LABEL_ORDER[pred_idx]
    probabilities = {label: float(p) for label, p in zip(_LABEL_ORDER, proba)}

    return {
        "host": host,
        "probabilities": probabilities,
        "sequence_length": len(sequence),
    }


def _main() -> None:
    parser = argparse.ArgumentParser(
        description="Predict influenza A host class from a PB2 amino-acid sequence."
    )
    parser.add_argument(
        "sequence",
        help="Single-letter amino-acid sequence (PB2 protein, ~759 residues).",
    )
    parser.add_argument(
        "--model",
        type=Path,
        default=_MODEL_PATH,
        help=f"Path to the saved RF model (default: {_MODEL_PATH})",
    )
    args = parser.parse_args()

    result = predict_host(args.sequence, model_path=args.model)

    print(f"\nPredicted host : {result['host'].upper()}")
    print(f"Sequence length: {result['sequence_length']} residues\n")
    print("Class probabilities:")
    for label, p in sorted(result["probabilities"].items(), key=lambda x: -x[1]):
        bar = "█" * int(p * 30)
        print(f"  {label:<8}  {p:.3f}  {bar}")
    print()


if __name__ == "__main__":
    _main()
